{{/*
Code generated by constago generator; DO NOT EDIT.
This file was produced from the scanning model and configuration.
*/}}

//go:build !ignore_autogenerated

package {{ .Package.Name }}

import (
{{- range $alias, $import := .Package.Imports }}
	{{ if $import.Alias }}{{ $import.Alias }}{{ else }}{{ $import.Name }}{{ end }} "{{ $import.Path }}"
{{- end }}
)

{{- range $struct := .Package.Structs }}
{{- if $struct.Constants }}
// Constants for {{ $struct.Name }}
const (
{{- range $constant := $struct.Constants }}
	{{ $constant.Name }} = "{{ $constant.Value }}"
{{- end }}
)

{{- end }}

{{- if $struct.Structs }}
{{- range $structOutput := $struct.Structs }}
// {{ $structOutput.Name }} contains field constants for {{ $struct.Name }}
type {{ $structOutput.Name }} struct {
{{- range $field := $structOutput.Fields }}
	{{ $field.Name }} string
{{- end }}
}

// New{{ $structOutput.Name }} creates a new {{ $structOutput.Name }} instance
func New{{ $structOutput.Name }}() *{{ $structOutput.Name }} {
	return &{{ $structOutput.Name }}{
{{- range $field := $structOutput.Fields }}
		{{ $field.Name }}: "{{ $field.Value }}",
{{- end }}
	}
}

{{- end }}
{{- end }}

{{- if $struct.Getters }}
{{- range $getter := $struct.Getters }}
// {{ $getter.Name }} returns the configured values for {{ $struct.Name }}
func (_struct *{{ $struct.Name }}) {{ $getter.Name }}() ({{- range $i, $return := $getter.Returns }}{{ if $i }}, {{ end }}{{ if $return.Constant }}string{{ else if $return.Field }}string{{ else if $return.None }}string{{ else if $return.Value }}{{ $return.Value.TypeName }}{{ end }}{{- end }}) {
	return {{ range $i, $return := $getter.Returns }}{{ if $i }}, {{ end }}{{ if $return.Constant }}"{{ $return.Constant.Value }}"{{ else if $return.Field }}"{{ $return.Field.Value }}"{{ else if $return.None }}"{{ $return.None.Value }}"{{ else if $return.Value }} _struct.{{ $return.Value.FieldName }}{{ end }}{{ end }}
}

{{- end }}
{{- end }}
{{- end }}